### ISSUE TITLE
[fix] build error(cause : _config.yaml)

### ISSUE THREAD

**Issue by inseo24** [inseo24/inseo24.github.io#3]
1. error 내용
/usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/theme.rb:84:in `rescue in gemspec': The just-the-docs theme could not be found. (Jekyll::Errors::MissingDependencyException)

2. 로컬에서 _config.yaml 은 theme: just-the-docs 을 추가하지 않으면 just-the-docs theme이 확인이 안됨

3. 문제는 로컬에서 돌릴 때는 저걸 추가해도 에러 없이 동작하지만 배포할 때 문제가 생김

4. 공식 문서에는 remote-theme에만 적용하거나 아니면 gem + theme 에 적용할 것을 예시로 들고 있음

5. 내가 현재 적용한 방식은 theme, remote-theme, gem 모두를 적용한 상태이므로 먼저 여기서 remote-theme 적용만 시도해보고, 로컬에서 도는거 테스트 해볼 거고

6. 그 다음 안되면 gem+theme으로 해볼 예정

**Comment by inseo24** [comment]
일단 로컬에서 theme: just-the-docs 적용 안하면 안되는 건 확실한 듯

**Comment by inseo24** [comment]
로컬에서 theme: just-the-docs를 적용하려면 gem에 just-the-docs를 써줘야 함
gem "just-the-docs"

안그러면 아래와 같이 gem에 없다고 뜨는데 _config.yaml에 적힌 디펜던시는 gemfile을 한 번 뒤져서 다운로드하는 시스템인듯.
빌드 에러가 나는 건 gem에서 다운이 되지 않아서 생기는 문제일까?

bundler: failed to load command: jekyll (/Users/seo/.rbenv/versions/3.1.1/bin/jekyll)
/Users/seo/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/jekyll-3.9.0/lib/jekyll/theme.rb:84:in `rescue in gemspec': The just-the-docs theme could not be found. (Jekyll::Errors::MissingDependencyException)

**Comment by inseo24** [comment]
local에서 gemfile에 just-the-docs를 써주면 해결되듯이 remote에서도 똑같이 적용되면 될 거 같은데 왜 안되는 걸까 
흠

**Comment by inseo24** [comment]
아 그래도 안됨 일단은 theme 삭제하고 로컬에서 돌릴 때만 추가해서 쓰자 
구글링하기엔 잠잘 시간 다가온다

**Comment by inseo24** [comment]
응 삭제하자마자 바로 빌드 잘 되죠?
gemfile에 써둬도 못 찾는거 킹 받죠?
just-the-docs 깃헙에 물어봐야겠다
